apiVersion: v1
kind: Service
metadata:
  labels:
    app: geoserver
  name: geoserver
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9090
    name: http
  selector:
    app: geoserver
  type: LoadBalancer
  sessionAffinity: ClientIP
